@startuml

skinparam componentStyle rectangle


component "GridBuilderHost\n<<EXE>>\n\nmain()\nImGui / DX11 Host\nverbindet Komponenten" as Host

component "DosBoxX\n<<Library>>\n\nView\nMouse\nKeyboard\nFrameReader\nFrameTexture\nController\nNamedPipeClient" as DosBoxX

component "dosbox-x\n<<EXE / Process>>" as DosBoxProcess

component "DosBoxMemoryTools\n<<Library>>\n\nMemoryReader\nMemoryScanner\nTracking\nDisassembly" as MemoryTools

component "MightAndMagic3ReverseEngineering\n<<Library>>\n\nMM3GameModule\nStateReader\nGameState\nMemoryAddresses\nScreenSignatures\nMM3 Navigation\nMM3 Item/Character Logic" as MM3

component "GridBuilderEditor\n<<Library>>\n\nWorldView\nMap / Chunk / Cell\nEditor Tools\nSerializer\nPixel Editor Integration" as Editor

HoHost --> DosBoxX : Controller / NamedPipeClient / FrameReader / FrameTexturest --> DosBoxX : Controller / FrameReader / FrameTexture
DosBoxX --> DosBoxProcess : startet / steuert / liest Frames

Host --> MemoryTools : benutzt

@enduml